-- MySQL Script generated by MySQL Workbench
-- Tue Jan  6 12:36:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema YOUTUBE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema YOUTUBE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `YOUTUBE` DEFAULT CHARACTER SET utf8 ;
USE `YOUTUBE` ;

-- -----------------------------------------------------
-- Table `YOUTUBE`.`CHANNEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`CHANNEL` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL DEFAULT '',
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`USER` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `gender` VARCHAR(20) NOT NULL DEFAULT 'not especified',
  `country` CHAR(3) NOT NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `CHANNEL_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `CHANNEL_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_USER_CHANNEL1_idx` (`CHANNEL_id` ASC) ,
  CONSTRAINT `fk_USER_CHANNEL1`
    FOREIGN KEY (`CHANNEL_id`)
    REFERENCES `YOUTUBE`.`CHANNEL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`VIDEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`VIDEO` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL DEFAULT '',
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `state` ENUM('privat', 'hidden', 'public') NOT NULL,
  `runtime` INT UNSIGNED NOT NULL,
  `size` BIGINT UNSIGNED NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `views_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `likes_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `dislikes_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `USER_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_VIDEO_USER1_idx` (`USER_id` ASC) ,
  CONSTRAINT `fk_VIDEO_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `YOUTUBE`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`TAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`TAG` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`PLAYLIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`PLAYLIST` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `state` ENUM('private', 'public') NOT NULL,
  `USER_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PLAYLIST_USER1_idx` (`USER_id` ASC) VISIBLE,
  CONSTRAINT `fk_PLAYLIST_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `YOUTUBE`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`COMMENTS` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USER_id` INT UNSIGNED NOT NULL,
  `VIDEO_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `USER_id`, `VIDEO_id`),
  INDEX `fk_COMMENTS_USER1_idx` (`USER_id` ASC) VISIBLE,
  INDEX `fk_COMMENTS_VIDEO1_idx` (`VIDEO_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMMENTS_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `YOUTUBE`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENTS_VIDEO1`
    FOREIGN KEY (`VIDEO_id`)
    REFERENCES `YOUTUBE`.`VIDEO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`VOTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`VOTES` (
  `type` ENUM('like', 'Dislike') NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USER_id` INT UNSIGNED NOT NULL,
  `VIDEO_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`USER_id`, `VIDEO_id`),
  INDEX `fk_VOTES_USER1_idx` (`USER_id` ASC) VISIBLE,
  INDEX `fk_VOTES_VIDEO1_idx` (`VIDEO_id` ASC) VISIBLE,
  CONSTRAINT `fk_VOTES_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `YOUTUBE`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VOTES_VIDEO1`
    FOREIGN KEY (`VIDEO_id`)
    REFERENCES `YOUTUBE`.`VIDEO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`SUBSCRIPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`SUBSCRIPTION` (
  `CHANNEL_id` INT UNSIGNED NOT NULL,
  `USER_id` INT UNSIGNED NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CHANNEL_id`, `USER_id`),
  INDEX `fk_table1_USER1_idx` (`USER_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_CHANNEL1`
    FOREIGN KEY (`CHANNEL_id`)
    REFERENCES `YOUTUBE`.`CHANNEL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `YOUTUBE`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`COMMENT_VOTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`COMMENT_VOTES` (
  `type` ENUM('like', 'dislike') NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS_id` INT UNSIGNED NOT NULL,
  `USER_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`COMMENTS_id`, `USER_id`),
  INDEX `fk_COMMENT_VOTES_USER1_idx` (`USER_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMMENT_VOTES_COMMENTS1`
    FOREIGN KEY (`COMMENTS_id`)
    REFERENCES `YOUTUBE`.`COMMENTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENT_VOTES_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `YOUTUBE`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`PLAYLIST_VIDEOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`PLAYLIST_VIDEOS` (
  `PLAYLIST_id` INT UNSIGNED NOT NULL,
  `VIDEO_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`PLAYLIST_id`, `VIDEO_id`),
  INDEX `fk_PLAYLIST_VIDEOS_VIDEO1_idx` (`VIDEO_id` ASC) VISIBLE,
  CONSTRAINT `fk_PLAYLIST_VIDEOS_PLAYLIST1`
    FOREIGN KEY (`PLAYLIST_id`)
    REFERENCES `YOUTUBE`.`PLAYLIST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYLIST_VIDEOS_VIDEO1`
    FOREIGN KEY (`VIDEO_id`)
    REFERENCES `YOUTUBE`.`VIDEO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YOUTUBE`.`VIDEO_TAGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YOUTUBE`.`VIDEO_TAGS` (
  `TAG_id` INT UNSIGNED NOT NULL,
  `VIDEO_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`TAG_id`),
  INDEX `fk_VIDEO_TAGS_VIDEO1_idx` (`VIDEO_id` ASC) VISIBLE,
  CONSTRAINT `fk_VIDEO_TAGS_TAG1`
    FOREIGN KEY (`TAG_id`)
    REFERENCES `YOUTUBE`.`TAG` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIDEO_TAGS_VIDEO1`
    FOREIGN KEY (`VIDEO_id`)
    REFERENCES `YOUTUBE`.`VIDEO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
